const Occasion = require('../models/Occasion');
const CATALOGUE = require('../data/occasions.json');

/**
 * Server-side twin of `frontend/src/celebrations/resolve.js`.
 *
 * Answers one question — "what is being celebrated on this IST day?" — using
 * the same catalogue (generated by `scripts/sync-occasions.js`) and the same
 * four date rules, so the morning push can never disagree with the header the
 * user then opens the app to see.
 *
 * Kept deliberately small: the app-side resolver also handles presentation,
 * memoisation and a year listing, none of which matter here.
 */

const IST_OFFSET_MS = (5 * 60 + 30) * 60 * 1000;

/**
 * Today's IST calendar day, as `{ key, year, month, day, weekday }`.
 *
 * The server may be running anywhere, so "today" is computed by shifting into
 * IST and reading the UTC fields — the same trick `attendanceReminderCron`
 * uses. The whole app's notion of a day is IST.
 */
function istToday(now = new Date()) {
  const ist = new Date(now.getTime() + IST_OFFSET_MS);
  const year = ist.getUTCFullYear();
  const month = ist.getUTCMonth();
  const day = ist.getUTCDate();
  const pad = (n) => String(n).padStart(2, '0');
  return {
    key: `${year}-${pad(month + 1)}-${pad(day)}`,
    year,
    month,
    day,
    weekday: ist.getUTCDay(),
  };
}

/** Easter Sunday by the anonymous Gregorian Computus — mirrors resolve.js. */
function easterSunday(year) {
  const a = year % 19;
  const b = Math.floor(year / 100);
  const c = year % 100;
  const d = Math.floor(b / 4);
  const e = b % 4;
  const f = Math.floor((b + 8) / 25);
  const g = Math.floor((b - f + 1) / 3);
  const h = (19 * a + b - d - g + 15) % 30;
  const i = Math.floor(c / 4);
  const k = c % 4;
  const l = (32 + 2 * e + 2 * i - h - k) % 7;
  const m = Math.floor((a + 11 * h + 22 * l) / 451);
  const n = h + l - 7 * m + 114;
  return { month: Math.floor(n / 31) - 1, day: (n % 31) + 1 };
}

/** Day-of-month of the nth given weekday in a month. */
function nthWeekdayOf(year, month, weekday, nth) {
  const firstDow = new Date(Date.UTC(year, month, 1)).getUTCDay();
  const offset = (weekday - firstDow + 7) % 7;
  return 1 + offset + (nth - 1) * 7;
}

function occursOn(occasion, today) {
  const when = occasion.when;
  if (!when) return false;

  switch (when.type) {
    case 'fixed':
      return today.month === when.month && today.day === when.day;

    case 'nthWeekday':
      return (
        today.month === when.month &&
        today.weekday === when.weekday &&
        today.day === nthWeekdayOf(today.year, when.month, when.weekday, when.nth)
      );

    case 'easter': {
      const easter = easterSunday(today.year);
      // Offsetting in UTC is safe here — this is pure calendar arithmetic on
      // already-resolved IST fields, not a timezone conversion.
      const shifted = new Date(Date.UTC(today.year, easter.month, easter.day + (when.offset || 0)));
      return shifted.getUTCMonth() === today.month && shifted.getUTCDate() === today.day;
    }

    case 'table': {
      const entry = when.dates?.[today.year];
      if (!entry) return false;
      return Array.isArray(entry) ? entry.includes(today.key) : entry === today.key;
    }

    case 'exact':
      return when.date === today.key;

    default:
      return false;
  }
}

/** Fold admin overrides into the catalogue — mirrors `applyOverrides`. */
function applyOverrides(catalogue, overrides) {
  if (!Array.isArray(overrides) || overrides.length === 0) return catalogue;

  const byKey = new Map(catalogue.map((o) => [o.key, o]));
  const added = [];

  for (const raw of overrides) {
    if (!raw || !raw.key) continue;
    const base = byKey.get(raw.key);

    if (base) {
      if (raw.muted) {
        byKey.delete(raw.key);
        continue;
      }
      const merged = { ...base };
      if (raw.name) merged.name = raw.name;
      if (raw.wish) merged.wish = raw.wish;
      if (Number.isFinite(raw.priority)) merged.priority = raw.priority;
      // Mirrors the app-side rule exactly, including the important part: a
      // corrected date on a FIXED occasion moves it but keeps it annual. See
      // the note in frontend/src/celebrations/resolve.js.
      if (raw.date && base.when?.type === 'table') {
        const year = Number(raw.date.slice(0, 4));
        merged.when = { type: 'table', dates: { ...base.when.dates, [year]: raw.date } };
      } else if (raw.date && base.when?.type === 'fixed') {
        const [, mm, dd] = raw.date.split('-').map(Number);
        merged.when = { type: 'fixed', month: mm - 1, day: dd };
      } else if (raw.date) {
        merged.when = { type: 'exact', date: raw.date };
      } else if (raw.recurring && Number.isInteger(raw.recurring.month)) {
        merged.when = { type: 'fixed', month: raw.recurring.month, day: raw.recurring.day };
      }
      byKey.set(raw.key, merged);
      continue;
    }

    const when = raw.date
      ? { type: 'exact', date: raw.date }
      : raw.recurring && Number.isInteger(raw.recurring.month)
        ? { type: 'fixed', month: raw.recurring.month, day: raw.recurring.day }
        : null;
    if (!when || raw.muted) continue;

    added.push({
      key: raw.key,
      name: raw.name || raw.key,
      wish: raw.wish || raw.name || 'Celebrating today',
      when,
      priority: Number.isFinite(raw.priority) ? raw.priority : 50,
      tags: raw.tags || [],
    });
  }

  return [
    ...catalogue.filter((o) => byKey.has(o.key)).map((o) => byKey.get(o.key)),
    ...added,
  ];
}

/**
 * What is being celebrated today (IST), highest priority first.
 * Reads overrides from Mongo; a database hiccup degrades to the bundled
 * catalogue rather than to silence.
 */
async function occasionsToday(now = new Date()) {
  const today = istToday(now);

  let overrides = [];
  try {
    overrides = await Occasion.find().lean();
  } catch (err) {
    console.error('[occasions] Could not read overrides, using bundled catalogue:', err.message);
  }

  const catalogue = applyOverrides(CATALOGUE.occasions, overrides);
  return catalogue
    .map((occasion, index) => ({ occasion, index }))
    .filter(({ occasion }) => occursOn(occasion, today))
    .sort((a, b) => (b.occasion.priority || 0) - (a.occasion.priority || 0) || a.index - b.index)
    .map(({ occasion }) => occasion);
}

module.exports = {
  istToday,
  easterSunday,
  occursOn,
  applyOverrides,
  occasionsToday,
  VERIFIED_THROUGH: CATALOGUE.verifiedThrough,
};
